pdf_front/mask/urls.py
from django.urls import path

from . import views

app_name = 'mask'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('post/', views.PostFormView.as_view(), name='post'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('post/<int:pk>/delete', views.PostDeleteView.as_view(), name='delete'),

]

pdf_front/pdf_front/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    # path('', include('mask.urls')),
    path('mask/', include('mask.urls')),
    path('admin/', admin.site.urls),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pdf_front/mask/models.py
from django.contrib.auth.hashers import is_password_usable, make_password
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _


class Post(models.Model):
    class Status(models.TextChoices):
        STAND_BY = 'SB', _('StandBy')
        PROCESSING = 'PR', _('Processing')
        FINISH = 'FN', _('Finish')
        ERROR = 'ER', _('Error')
        DELETE_USER = 'DU', _('Deleted by User')
        EXPIRED = 'EX', _('Expired')

    title = models.CharField(max_length=30)
    author = models.CharField(max_length=10)
    password = models.CharField(max_length=60)
    image = models.ImageField(default=None, upload_to='origin/%Y/%m/%d', null=True)
    mask_method = models.CharField
    result_image = models.ImageField(blank=True, upload_to='mask/%Y/%m/%d')
    status = models.CharField(
        max_length=2,
        choices=Status.choices,
        default=Status.STAND_BY
    )
    reg_date = models.DateTimeField(auto_now_add=True)
    mod_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        mod_date = self.mod_date.strftime("%Y%m%d_%H:%M:%S") if self.mod_date is not None else None
        mod_date = "({})".format(mod_date) if mod_date is not None else ""
        name = "{title} - {author} - {status}{mod_date} - {reg_date}".format(
            title=self.title,
            author=self.author,
            status=self.status,
            reg_date=self.reg_date.strftime("%Y%m%d_%H:%M:%S"),
            mod_date=mod_date
        )
        return name


# @receiver(pre_save, sender=Request)
# def password_hashing(instance, **kwargs):
#     if not is_password_usable(instance.password):
#         instance.password = make_password(instance.password)

pdf_front/mask/forms.py
from django.forms import ModelForm, forms, TextInput, PasswordInput, FileInput
from .models import Post

from django.utils.translation import gettext_lazy as _


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'author', 'password', 'image']
        widgets = {
            'title': TextInput(attrs={'class': 'form-control', 'placeholder': "30자 이내로 입력 가능합니다."}),
            'author': TextInput(attrs={'class': 'form-control', 'placeholder': "10자 이내로 입력 가능합니다."}),
            'password': PasswordInput(
                attrs={'class': 'form-control', 'placeholder': "20자 이내로 입력해주세요.", 'required': 'true'}),
            'image': FileInput(attrs={'class': 'form-control-file', 'placeholder': "이미지 혹은 영상을 업로드해주세요."}),

        }

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['maxlength'] = 30
        self.fields['author'].widget.attrs['maxlength'] = 10
        self.fields['password'].widget.attrs['maxlength'] = 20
        self.fields['image'].required = True

    def save(self, commit=True):
        self.instance = Post(**self.cleaned_data)
        if commit:
            self.instance.save()
        return self.instance

pdf_front/mask/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.http import HttpResponse
from django.views.generic import ListView, DetailView, View, FormView

from .forms import PostForm
from .models import Post
from .utils import encrypt, check_pw, get_alert, set_alert


def index(req, **kwargs):
    return render(req, 'mask/index.html')


class IndexView(ListView):
    template_name = 'mask/index.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.order_by('-reg_date')[:5]


class PostDetailView(View):

    def get(self, req, pk):
        context = {}
        try:
            post = Post.objects.get(pk=pk)
            context['post'] = post
            set_alert(req, "이미지를 보려면, 암호를 입력하셔야 합니다.", type="INFO")
            return render(req, 'mask/check_password.html', context)
        except Exception:
            set_alert(req, "The post was not found.", "ERROR", type="DANGER")
            context['posts'] = Post.objects.order_by('-reg_date')

            return render(req, 'mask/index.html', context)

    def post(self, req, pk):
        context = {}

        try:
            if 'password' not in req.POST.keys():
                set_alert(req, "Error", "ERROR", "DANGER")

            input_pw = req.POST['password']
            post = Post.objects.get(pk=pk)
            context['post'] = post
            hashed_pw = post.password
            if check_pw(input_pw, hashed_pw):
                # context['alert'] = get_alert("Password match!", type="SUCCESS")
                if post.status == Post.Status.STAND_BY:
                    set_alert(req, "작업 대기중입니다.", type="NORMAL")
                else:
                    set_alert(req, title="작업 완료!", msg="아래 다운로드 버튼을 눌러보세요!", type="SUCCESS")

                return render(req, 'mask/detail.html', context)
            else:
                set_alert(req, "비밀번호가 틀립니다.", type="DANGER")

                return render(req, 'mask/check_password.html', context)
        except Exception:
            set_alert(req, "The post was not found.", type="WARN")
            return render(req, 'mask/index.html', context)


class _PostDetailView(DetailView):
    model = Post
    template_name = 'mask/detail.html'


class PostFormView(FormView):
    def get(self, request, **kwargs):
        form = PostForm()
        context = {'form': form}
        return render(request, 'mask/post.html', context=context)

    def post(self, request, **kwargs):
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            #
            post.password = encrypt(post.password)
            post.save()
            pk = post.pk
            return redirect('mask:detail', pk=pk)


class PostDeleteView(View):
    def get(self, req, pk):
        context = {}
        try:
            post = Post.objects.get(pk=pk)
            context['post'] = post
            set_alert(req, "이미지를 삭제하려면, 암호를 입력하셔야 합니다.", type="INFO")
            return render(req, 'mask/check_password.html', context)
        except Exception:
            set_alert(req, "The post was not found.", "ERROR", type="DANGER")
            context['posts'] = Post.objects.order_by('-reg_date')

            return render(req, 'mask/index.html', context)

    def post(self, req, pk):
        context = {}

        try:
            if 'password' not in req.POST.keys():
                set_alert(req, "Error", type="DANGER")
            input_pw = req.POST['password']
            post = Post.objects.get(pk=pk)
            context['post'] = post
            hashed_pw = post.password
            if check_pw(input_pw, hashed_pw):
                post.delete()
                set_alert(req, "삭제되었습니다.", type="SUCCESS")

                return render(req, 'mask/index.html', context)
            else:
                set_alert(req, "비밀번호가 틀립니다.", type="DANGER")

                return render(req, 'mask/check_password.html', context)
        except Exception:
            set_alert(req, "The post was not found.", type="WARN")
            return render(req, 'mask/index.html', context)

pdf_front/templates/mask/base.html
{% load static %}
{% load template_utils %}

<!DOCTYPE html>
<html lang="ko-kr">
<head>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>

    <title>{% block title %}PDF{% endblock title %}</title>

</head>
<body>

{% block navbar %}
    <nav class="navbar navbar-expand-sm navbar-light bg-light mb-3">
        <div class="container">
            <a href="/" class="navbar-brand">PDF</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item"><a href="{% url 'mask:index' %}" class="nav-link">Blur</a></li>

                    <li class="nav-item"><a href="https://github.com/jholee"
                                            class="nav-link">..</a></li>
                </ul>
            </div>
        </div>
    </nav>
{% endblock navbar %}
<div class="container">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            {% block breadcrumb %}

                <li class="breadcrumb-item active" aria-current="page">mask</li>

            {% endblock breadcrumb %}
        </ol>
    </nav>
    {{ request | show_alert | safe }}


    {% block container %}
    {% endblock container %}
</div>
</body>
</html>

pdf_front/templates/mask/check_delete.html
{% extends "mask/base.html" %}

{% load template_utils %}

{% load static %}

{% block title %}
    {{ block.super }} :: blur
{% endblock title %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'mask:index' %}">mask</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ post.id }}</li>
{% endblock breadcrumb %}

{% block container %}


    <div class="jumbotron">
    <small>{{ msg }}</small>
        <h1>{{ post.title }}</h1>
        <hr class="my-3">
        <dl class="row">
            <dt class="col-sm-2 ">{{ _('reg_date') }}</dt>
            <dd class="col-sm-4">{{ post.reg_date }}</dd>

            <dt class="col-sm-2">{{ _('author') }}</dt>
            <dd class="col-sm-4">{{ post.author }}</dd>

            <dt class="col-sm-2">{{ _('status') }}</dt>
            <dd class="col-sm-4">{{ post.get_status_display }}</dd>

            <dt class="col-sm-2">{{ _('mod_date') }}</dt>
            {% if post.mod_date %}
                <dd class="col-sm-4">{{ post.mod_date }}</dd>
            {% else %}
                <dd class="col-sm-4">Not Yet</dd>
            {% endif %}
        </dl>
        <hr class="my-3">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="inputPassword" class=" ">{{ _('Password') }}</label>
                <input type="password" class="form-control" id="inputPassword" name="password" placeholder="*****"
                       required>
                <small id="passwordHelpBlock" class="form-text text-muted">
                    Your password will be encrypted and nobody can't decrypt.
                </small>
            </div>
            <button type="submit" class="btn btn-lg btn-success btn-block">{{ _('OK') }}</button>
        </form>

    </div>
    <hr class="my-1">


{% endblock container %}

pdf_front/templates/mask/check_password.html
{% extends "mask/base.html" %}

{% load template_utils %}

{% load static %}

{% block title %}
    {{ block.super }} :: blur
{% endblock title %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'mask:index' %}">mask</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ post.id }}</li>
{% endblock breadcrumb %}

{% block container %}


    <div class="jumbotron">
    <small>{{ msg }}</small>
        <h1>{{ post.title }}</h1>
        <hr class="my-3">
        <dl class="row">
            <dt class="col-sm-2 ">{{ _('reg_date') }}</dt>
            <dd class="col-sm-4">{{ post.reg_date }}</dd>

            <dt class="col-sm-2">{{ _('author') }}</dt>
            <dd class="col-sm-4">{{ post.author }}</dd>

            <dt class="col-sm-2">{{ _('status') }}</dt>
            <dd class="col-sm-4">{{ post.get_status_display }}</dd>

            <dt class="col-sm-2">{{ _('mod_date') }}</dt>
            {% if post.mod_date %}
                <dd class="col-sm-4">{{ post.mod_date }}</dd>
            {% else %}
                <dd class="col-sm-4">Not Yet</dd>
            {% endif %}
        </dl>
        <hr class="my-3">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="inputPassword" class=" ">{{ _('Password') }}</label>
                <input type="password" class="form-control" id="inputPassword" name="password" placeholder="*****"
                       required>
                <small id="passwordHelpBlock" class="form-text text-muted">
                    Your password will be encrypted and nobody can't decrypt.
                </small>
            </div>
            <button type="submit" class="btn btn-lg btn-success btn-block">{{ _('OK') }}</button>
        </form>

    </div>
    <hr class="my-1">


{% endblock container %}

pdf_front/templates/mask/detail.html
{% extends "mask/base.html" %}

{% load static %}
{% load template_utils %}

{% block title %}
    {{ block.super }} :: blur
{% endblock title %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'mask:index' %}">mask</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ post.id }}</li>
{% endblock breadcrumb %}

{% block container %}

    {% if post.result_image %}
        <a href="{{ post.result_image.url }}">
            <button type="button" class="btn btn-lg btn-block btn-success">Download Result</button>
        </a>
        <hr class="my-1">
    {% endif %}
    <a href="{% url 'mask:delete' post.pk %}">
        <button type="button" class="btn btn-lg btn-block btn-danger">Delete</button>
    </a>
    <hr class="my-1">
    <div class="jumbotron">
    <small>{{ msg }}</small>
        <h3 class="display-4">{{ post.title }}</h3>
        <hr class="my-3">
        <dl class="row">
            <dt class="col-sm-2 ">reg_date</dt>
            <dd class="col-sm-4">{{ post.reg_date }}</dd>

            <dt class="col-sm-2">author</dt>
            <dd class="col-sm-4">{{ post.author }}</dd>

            <dt class="col-sm-2">status</dt>
            <dd class="col-sm-4">{{ post.get_status_display }}</dd>

            <dt class="col-sm-2">mod_date</dt>
            {% if post.mod_date %}
                <dd class="col-sm-4">{{ post.mod_date }}</dd>
            {% else %}
                <dd class="col-sm-4">Not Yet</dd>
            {% endif %}
        </dl>
        <hr class="my-2">
        <h4>Original Image</h4>
        {% if post.image %}
            <img class="img-fluid" src="{{ post.image.url }}" alt="Posted Image">
        {% else %}
            <img class="img-fluid" src="{% static 'image_not_found.png' %}" alt="Image Not Found">
        {% endif %}
        {% if post.result_image %}
            <hr class="my-2">
            <h4>Masked Image</h4>
            <img class="img-fluid" src="{{ post.result_image.url }}" alt="Masked Image">
        {% endif %}

    </div>




{% endblock container %}

pdf_front/templates/mask/index.html
{% extends "mask/base.html" %}

{% load template_utils %}

{% block title %}
    {{ block.super }} :: blur
{% endblock title %}

{% block container %}


    <a href="{% url 'mask:post' %}">
        <button type="button" class="btn btn-lg btn-outline-success btn-block">요청하기</button>
    </a>

    <hr class="my-1">

    <div id="post-list-group" class="list-group">
        <div class="list-group-item list-group-item-action active">
            <h3 class="align-items-center">요청 목록</h3>
        </div>

        {% for item in posts %}
            <a href="{% url 'mask:detail' item.id %}" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ item.id }}</h5>
                    <small>{{ item.reg_date }}</small>
                </div>
                {% if item.mod_date %}
                    <p class="mb-1">{{ item.get_status_display }} - {{ item.mod_date }}</p>
                {% else %}
                    <p class="mb-1">{{ item.get_status_display }}</p>
                {% endif %}
                <small>{{ item.author }}</small>
            </a>
        {% endfor %}

    </div>

{% endblock container %}

pdf_front/templates/mask/post.html
{% extends "mask/base.html" %}

{% load template_utils %}

{% block title %}
    {{ block.super }} :: blur
{% endblock title %}
{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'mask:index' %}">mask</a></li>
    <li class="breadcrumb-item active" aria-current="page">new</li>
{% endblock %}
{% block container %}

    <form method="POST" action="" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="jumbotron">
            <h2>마스킹 요청</h2>
            {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field.as_widget }}
                    <small id="{{ field.auto_id }}Help" class="form-text text-muted">{{ field.help_text }}</small>
                </div>
            {% endfor %}


        </div>
        <hr class="my-4">

        <button type="submit" class="btn btn-success btn-lg btn-block">등록</button>
        <br>
        <a href="{% url 'mask:index' %}">
            <button type="button" class="btn btn-outline-danger btn-lg btn-block">취소</button>
        </a>
    </form>


{% endblock container %}